apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fhui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-fhui@sha256:5e1866982456ec2224a7d3692f60b03768560ad4da42414aff9c6ac8ee77bd8a
        name: my-nodejs
        resources: {}
status: {}
